### PR TITLE
Fast forward

### PR DESCRIPTION
**Pull request by donnaqi**
#77

### CODE REVIEW

**Comment by donnaqi** [comment]
I'm fixing right now: the fast forward should do nothing when the time is stopped

**Comment by donnaqi** [comment]
Right now, disabling R when fast forwarding, but then I add enable R at the start of a time loop to avoid the bug happening when pressing fast forward all the way until the new loop starts and R is still disabled; let me know if that's appropriate.

**Review by wang-henry — APPROVED** [review]

**Comment by ectodrop** [comment]
After testing it, it seems like after you hold F and let the time end, the movements are still disabled after the scene restarts, should probably be changed so that the movements are enabled on start.

**Comment by donnaqi** [comment]
> After testing it, it seems like after you hold F and let the time end, the movements are still disabled after the scene restarts, should probably be changed so that the movements are enabled on start.

Fixed in this commit: [0bf9f23](https://github.com/ectodrop/loop-game/pull/114/commits/0bf9f23fb90ed45080f81fa25dc1e54df228450d)

**Review by ectodrop — APPROVED** [review]

**Pull request merged**
